Update dependencies to non-staging 3.0.0 versions.
adobe/aepsdk-edgebridge-android pull request #76
Opened 2024-04-01 21:15 UTC by kevinlind

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-04-01 21:47 UTC, emdobrin reviewed
can you also include the readme/doc changes for test app run?

2024-04-01 21:47 UTC, emdobrin commented on code/app/build.gradle.kts
> +    implementation("com.adobe.marketing.mobile:core:3.0.0")
should we use mavenCoreVersion instead, similar to the other extensions

2024-04-01 21:47 UTC, emdobrin commented on code/gradle.properties
>  # Mobile Core dependency version
could we clean this file up similar to the other extensions - e.g. https://github.com/adobe/aepsdk-edgeidentity-android/blob/staging/code/gradle.properties

2024-04-01 22:28 UTC, cacheung reviewed
Can you also update the readme for this sentence
To open and run the project, open the code/settings.gradle.kt file in Android Studio

2024-04-01 23:46 UTC, cacheung approved these changes

2024-04-01 23:54 UTC, cacheung requested changes
Please update the readme.

2024-04-02 01:25 UTC, emdobrin approved these changes

2024-04-02 05:39 UTC, cacheung approved these changes

2024-04-02 21:11 UTC, merged